version: '3'

services:
    service-name-registry:
        build: ./service-name-registry
        ports:
            - "3001:80"
            - "5001:5001"

    service-hello:
        build: ./service-hello
        ports:
            - "3002:80"
            - "5002:5002"
        depends_on:
            - service-name-registry
            - db

    db:
        image: postgres
        ports:
            - "3003:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: namesdb
